[package]
name = "citadel-mount"
version = "0.1.0"
authors = ["Bruce Leidl <bruce@subgraph.com>"]
homepage = "http://github.com/subgraph/citadel"

[dependencies]
libcitadel = { path = "../libcitadel" }
libc = "0.2"
failure = "0.1.3"
